services:
  domino-parejas:
    container_name: domino-parejas
    image: joanalba/domino-parejas:latest
    ports:
      - "80:80"      # frontend
      - "8000:8000"  # backend API
      - "5433:5432"  # PostgreSQL (puerto externo 5433, interno 5432)
    volumes:
      - ./secrets:/app/secrets:ro
      - postgres_data:/var/lib/postgresql/data
    environment:
      - ENV=production
      - APP_ENV=production
      - POSTGRES_USER=domino
      - POSTGRES_DB=domino_app
      - POSTGRES_PASSWORD_FILE=/app/secrets/db_password.txt
      - CORS_ORIGINS=http://localhost,http://localhost:80,http://0.0.0.0:80,http://domino-parejas
      - SECRET_KEY_FILE=/app/secrets/secret_key.txt
      - JWT_SECRET_KEY_FILE=/app/secrets/jwt_secret_key.txt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - domino-net

volumes:
  postgres_data:
    name: domino-parejas-data

networks:
  domino-net:
    name: domino-parejas-network
    external: false 