version: '3.9'

services:
  domino-parejas:
    container_name: domino-parejas
    image: joanalba/domino-parejas:latest
    platform: linux/amd64
    ports:
      - "80:80"      # frontend
      - "8000:8000"  # backend
    volumes:
      - ./secrets:/app/secrets:ro
    environment:
      - ENV=production
      - APP_ENV=production
      - DATABASE_URL=postgresql://postgres:$$(cat /app/secrets/db_password.txt)@db:5432/domino_parejas
      - CORS_ORIGINS=http://localhost,http://localhost:80
      - SECRET_KEY=$$(cat /app/secrets/secret_key.txt)
      - JWT_SECRET_KEY=$$(cat /app/secrets/jwt_secret_key.txt)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - domino-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    platform: linux/amd64
    container_name: domino-parejas-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$$(cat /run/secrets/db_password)
      - POSTGRES_DB=domino_parejas
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./secrets/db_password.txt:/run/secrets/db_password:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - domino-net

volumes:
  postgres_data:
    name: domino-parejas-data

networks:
  domino-net:
    name: domino-parejas-network
    external: false 