"""add rt and mg fields to resultado

Revision ID: fbf1aa575a28
Revises: 
Create Date: 2025-01-29 09:17:15.518080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf1aa575a28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultados', sa.Column('rt', sa.Integer(), nullable=True))
    op.add_column('resultados', sa.Column('mg', sa.Integer(), nullable=True))
    op.drop_constraint('resultados_campeonato_id_fkey', 'resultados', type_='foreignkey')
    op.drop_constraint('resultados_pareja_id_fkey', 'resultados', type_='foreignkey')
    op.create_foreign_key(None, 'resultados', 'campeonatos', ['campeonato_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'resultados', 'parejas', ['pareja_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resultados', type_='foreignkey')
    op.drop_constraint(None, 'resultados', type_='foreignkey')
    op.create_foreign_key('resultados_pareja_id_fkey', 'resultados', 'parejas', ['pareja_id'], ['id'])
    op.create_foreign_key('resultados_campeonato_id_fkey', 'resultados', 'campeonatos', ['campeonato_id'], ['id'])
    op.drop_column('resultados', 'mg')
    op.drop_column('resultados', 'rt')
    # ### end Alembic commands ###
